### ISSUE TITLE
nameParts[j] should be updated to namePartWords[j]

### ISSUE THREAD

**Issue by art-ortega** [RateGravity/parse-full-name#23] opened 2021-06-25 21:00 UTC
https://github.com/RateGravity/parse-full-name/blob/9bc524845becd893fc0a05934518dbfaed0f3efa/index.js#L73

Line 73 and Line 74

**Comment by chris-pardy** [comment] 2021-09-21 14:40
Please provide a description of the issue that is being caused by this bug rather than a simple fix.

**Comment by chris-pardy** [comment] 2021-09-24 14:44
Resolved in release 1.2.6

**Closed by chris-pardy** 2021-09-24 14:44 UTC
